export const ErrorCode = {
  PARSE_FAILED: 'PARSE_FAILED',
  UNSUPPORTED_COMMAND: 'UNSUPPORTED_COMMAND',
  MISSING_DATABASE: 'MISSING_DATABASE',
  INVALID_METHOD: 'INVALID_METHOD',
  INVALID_DATABASE: 'INVALID_DATABASE',
  DANGEROUS_OPERATION: 'DANGEROUS_OPERATION',
  MULTI_STATEMENT: 'MULTI_STATEMENT',
  READONLY_VIOLATION: 'READONLY_VIOLATION',
} as const;
