export function isPoolConnection(id: string): boolean {
  return id.startsWith('conn_');
}

export const ErrorCode = {
  CONNECTION_NOT_FOUND: 'CONNECTION_NOT_FOUND',
  NOT_CONNECTED: 'NOT_CONNECTED',
  PARSE_FAILED: 'PARSE_FAILED',
  UNSUPPORTED_COMMAND: 'UNSUPPORTED_COMMAND',
  MISSING_DATABASE: 'MISSING_DATABASE',
  INVALID_METHOD: 'INVALID_METHOD',
  QUERY_FAILED: 'QUERY_FAILED',
  INVALID_DATABASE: 'INVALID_DATABASE',
  DANGEROUS_OPERATION: 'DANGEROUS_OPERATION',
  MULTI_STATEMENT: 'MULTI_STATEMENT',
  READONLY_VIOLATION: 'READONLY_VIOLATION',
} as const;
